apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - namespace.yaml
  - helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: oncall
  app.kubernetes.io/part-of: monitoring-stack
