apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - daemonset.yaml
  - runtimeclass.yaml
commonLabels:
  app.kubernetes.io/name: nvidia-device-plugin
  app.kubernetes.io/part-of: gpu-infrastructure
images:
  - name: nvcr.io/nvidia/k8s-device-plugin
    newTag: v0.17.0
