apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/part-of: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxmox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxmox-exporter
        app.kubernetes.io/part-of: monitoring-stack
    spec:
      containers:
        - name: proxmox-exporter
          image: prompve/prometheus-pve-exporter:3.4.6
          ports:
            - name: metrics
              containerPort: 9221
              protocol: TCP
          env:
            - name: PVE_VERIFY_SSL
              value: "false"
          envFrom:
            - secretRef:
                name: proxmox-exporter-credentials
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
