apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app.kubernetes.io/name: proxmox-exporter
  app.kubernetes.io/part-of: monitoring-stack

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
