apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/part-of: monitoring-stack
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9221"
    prometheus.io/path: "/pve"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9221
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: proxmox-exporter
