apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../base
  - sealed-secrets.yaml
commonAnnotations:
  app.kubernetes.io/instance: korriban
patches:
  - path: patches/storage-patch.yaml
