apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../base
  - sealed-secrets.yaml
  - istio-routing.yaml
  - storage.yaml
commonAnnotations:
  app.kubernetes.io/instance: korriban
