apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
    instance: korriban
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9221"
    prometheus.io/path: "/pve"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9221
      targetPort: 9221
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
    instance: korriban
subsets:
  - addresses:
      - ip: 10.10.6.96
    ports:
      - name: metrics
        port: 9221
        protocol: TCP
