apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - configmap-settings.yaml
  - searxng-deployment.yaml
commonLabels:
  app.kubernetes.io/name: searxng
  app.kubernetes.io/part-of: search-stack
