apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - pvc.yaml
  - configmap-datasources.yaml
  - configmap-grafana-ini.yaml
  - deployment.yaml
  - service.yaml
  - dashboards/proxmox-dashboard-configmap.yaml
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoring-stack
