apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus
  - grafana
  - alloy
  - prometheus-node-exporter
  - kube-state-metrics
  - webhook-receiver
  - metrics-server
  - loki
  - alertmanager
  - cloudflared
  - nebula-sync-pihole1
  - nebula-sync-pihole3
  - nebula-sync-pihole5
  - plex-monitoring
  - proxmox-monitoring
  - n8n
  - pyroscope
  - tempo
  - renovate
  - searxng
  - immich
  - oncall
