apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - kustomization-infrastructure.yaml
  - kustomization-apps.yaml
  - gitrepository-private.yaml
  - kustomization-media-apps.yaml
