---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-storage
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-private
  path: ./clusters/korriban/infrastructure/storage
  prune: true
  timeout: 2m0s
