apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  values:
    cloudflare:
      tunnelId: "498c5bc5-3084-4539-9905-31b586deafba"
      tunnelName: "korriban-k8s"
      ingress:
        - hostname: n8n.home.cwbtech.net
          service: http://n8n.n8n.svc.cluster.local:5678
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
