apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv-arr-downloads.yaml
  - pv-arr-complete.yaml
  - pv-radarr-media.yaml
  - pv-sonarr-media.yaml
  - pvc-arr-downloads.yaml
  - pvc-arr-complete.yaml
  - pvc-radarr-media.yaml
  - pvc-sonarr-media.yaml
