apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - redis-deployment.yaml
  - n8n-deployment.yaml
  - n8n-worker-deployment.yaml
commonLabels:
  app.kubernetes.io/name: n8n
  app.kubernetes.io/part-of: n8n
