apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semaphore
resources:
  - ../../base
  - sealed-secrets.yaml
  - istio-routing.yaml
commonAnnotations:
  app.kubernetes.io/instance: korriban
patches:
  - path: patches/domain-patch.yaml
    target:
      kind: Deployment
      name: semaphore
patchesStrategicMerge:
  - patches/storage-patch.yaml
