apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng
resources:
  - ../../base
  - sealed-secrets.yaml
  - istio-routing.yaml
commonAnnotations:
  app.kubernetes.io/instance: korriban
patchesStrategicMerge:
  - patches/storage-patch.yaml
